### ISSUE TITLE
cannot import name 'PipelineHelper' from 'pipelinehelper' (unknown location)

### ISSUE THREAD

**Issue by browshanravan** [bmurauer/pipelinehelper#6]
I have downloaded the `pipelinehelper` into my virtual environment using the code

`pip3 install git+https://github.com/bmurauer/pipelinehelper.git`

however when I call the function using 

```python3
from pipelinehelper import PipelineHelper
```
I get the error `cannot import name 'PipelineHelper' from 'pipelinehelper' (unknown location)`

Many thanks in advance.

**Comment by bmurauer** [comment]
hi,
I have just updated the project and published it on PyPI, so now you should be able to install it using pip directly:

    pip install pipelinehelper

Then, the above import should work

**Comment by browshanravan** [comment]
It works! thank you.
