### ISSUE TITLE
RandomizedSearchCV compatibility?

### ISSUE THREAD

**Issue by browshanravan** [bmurauer/pipelinehelper#8]
The instruction page says `pipelinehelper` is specifically designed to work with `GridSearchCV`. Although I haven't tried it yet but are there any plans to make it compatible with `RandomizedSearchCV`? This will dramatically reduce my computation time.

**Comment by bmurauer** [comment]
While I have not yet tried this, I don't suspect that there will be great complications I think. I'll leave this ticket opened until I test things thoroughly, thanks for the suggestion :)

**Comment by bmurauer** [comment]
My test cases seem to suggest that it functions the way it is, I will update the readme accordingly
